# from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings
import os


# Why all-MiniLM-L6-v2?
# It is the most widely used open-source embedding model.
# 384 dimensions — small enough to be fast on CPU.
# Trained on 1 billion sentence pairs — strong semantic understanding.
# Used in production by companies that cannot use commercial APIs
# due to data privacy requirements — exactly our legal use case.
#
# Alternatives we considered:
# - OpenAI text-embedding-3-small: better accuracy but data leaves machine
# - all-mpnet-base-v2: slightly better quality but 2x slower
# - BGE-large: best open source quality but requires GPU
# Decision: MiniLM gives 90% of the quality at 100% privacy and zero cost.

EMBEDDING_MODEL = "all-MiniLM-L6-v2"


def get_embedder():
    """
    Returns a HuggingFace embedding model that runs locally.

    First call downloads the model (~90MB) to your machine.
    Every call after that uses the cached local copy.
    No internet required after first download.
    No API key. No cost. No data leaving the machine.

    This is your data privacy answer in interview:
    "Embeddings are generated locally using sentence-transformers.
    The contract text never leaves the client's infrastructure."
    """

    embedder = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL,
        model_kwargs={"device": "cpu"},  # CPU is fine for this model
        encode_kwargs={
            "normalize_embeddings": True
            # Why normalize?
            # Normalized vectors make cosine similarity = dot product.
            # This is faster and more stable for retrieval.
            # Standard practice for production embedding pipelines.
        }
    )

    return embedder


def get_embedding_info() -> dict:
    """
    Returns info about the embedding setup.
    Use this in your interview to show you understand the system:
    "Our embeddings are 384-dimensional vectors generated by
    all-MiniLM-L6-v2 running locally — 90MB model, CPU inference,
    zero data egress."
    """
    return {
        "model": EMBEDDING_MODEL,
        "dimensions": 384,
        "device": "cpu",
        "normalized": True,
        "data_egress": False,
        "cost": 0
    }